steps:
- name: gcr.io/cloud-builders/docker
  args:
    [
      "build",
      "-t",
      "us-central1-docker.pkg.dev/$PROJECT_ID/rag-eval-repo/api:ci-test",
      "."
    ]

- name: gcr.io/cloud-builders/docker
  args:
    [
      "push",
      "us-central1-docker.pkg.dev/$PROJECT_ID/rag-eval-repo/api:ci-test"
    ]

images:
- us-central1-docker.pkg.dev/$PROJECT_ID/rag-eval-repo/api:ci-test
