apiVersion: v1
kind: ResourceQuota
metadata:
  name: gpu-capacity-quota
spec:
  hard:
    requests.cpu: "24"
    requests.memory: 96Gi
    limits.cpu: "32"
    limits.memory: 128Gi
    requests.nvidia.com/gpu: "8"
    limits.nvidia.com/gpu: "8"
    pods: "60"
