apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  labels:
    app.kubernetes.io/name: vllm-gpu-inference
spec:
  selector:
    app.kubernetes.io/name: vllm-gpu-inference
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
